test:
	pytest ./tests/

test_data:
	pytest -rc ./tests/test_data.py

test_code:
	pytest -rc ./tests/test_code.py

test_model:
	pytest -ss ./tests/test_model.py

test_all:
	pytest --cov=mnist_train tests/
