apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-app-server
  template:
    metadata:
      labels:
        app: deploy-app-server
    spec:
      containers:
      - name: app-server
        image: 8092/app-server:latest
---
apiVersion: v1
kind: Service
metadata:
  name: deploy-app-server
  labels:
    app: deploy-app-server
spec:
  selector:
    app: deploy-app-server
  ports:
  - port: 8000
    protocol: TCP
