# creating persistent volume

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv
  labels:
    app: minio-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi