dir_data: data/
dir_log: logs/
dir_weights: weights/checkpoint_stage1
seed: 17
image_size: 28

train_params:
  batch_size: 64
  epochs: 10
  lr: 1.0
  gamma: 0.7

data:
  num_workers: 4
  shuffle: true
  pin_memory: true
  normalize_mean: 0.1307
  normalize_std: 0.3081

logs:
  log_train_loss: 10
  log_test_loss: 200
  log_weights: 500

model_card:
  project_name: ml-in-production
