name: week-2-ci

on:
  push:
    branches:
      - 'main'
      - 'week-2'

jobs:
  launch-minio:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Start minikube
        uses: medyagh/setup-minikube@master
      -
        name: Create persistent volume
        run: kubectl create -f week-2/minio/pv.yaml

      - name: Create services
        run: kubectl create -f week-2/minio/services.yaml

      - name: Create deployment
        run: kubectl create -f week-2/minio/deployment.yaml

      - name: Try the cluster!
        run: kubectl get pods -A
